image: "maven"

stages:
  - build
  - test
  - package

variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/"

install:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean org.jacoco:jacoco-maven-plugin:prepare-agent install
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - ".m2/"
  artifacts:
    when: on_success
    expire_in: 5 days
    paths:
      - "*/target"
      - "*/*/target"
      - "*/*/*/target"

sonar_scan:
  stage: test
  only:
    refs:
      - develop
    variables:
      - $SONAR_URL
      - $SONAR_TOKEN
      - $SONAR_PROJECT_KEY
  dependencies:
    - install
  script:
    - ./ci/test/sonar_scan.sh

clamav_scan:
  variables:
    SCAN_LOG: "av.log"
    DEFINITIONS_PATH: ".clamav/"
  stage: test
  dependencies:
    - install
  image:
    name: alpine
  cache:
    key: clamav-definitions
    paths:
      - ${DEFINITIONS_PATH}
  script:
    - ./ci/test/clamav_scan.sh ${SCAN_LOG} ${DEFINITIONS_PATH}
  artifacts:
    paths:
      - ${SCAN_LOG}

build:
  stage: package
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --skip-tls-verify --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
#  only:
#    - tags

include:
  - local: /ci/test/blackduck/.gitlab-ci.yml
