image: "maven"

stages:
  - version
  - build
  - test
  - deploy
  - dast

variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/"

before_script:
  - if [ $(command -v mvn)  ] && [ -f "version" ] ; then mvn -B versions:set -DnewVersion=$(cat version) -DprocessAllModules ; fi

install:
  stage: build
  only:
    - branches
    - tags
    - merge_requests
  script:
    - mvn $MAVEN_CLI_OPTS clean org.jacoco:jacoco-maven-plugin:prepare-agent install
  cache:
    key: ${CI_COMMIT_REF_SLUG}-maven
    paths:
      - ".m2/"
  artifacts:
    when: on_success
    expire_in: 5 days
    paths:
      - "*/target"
      - "*/*/target"
      - "*/*/*/target"
    reports:
      junit:
        - "**/target/surefire-reports/TEST-*.xml"
        - "**/target/failsafe-reports/TEST-*.xml"

include:
  - local: /ci/test/blackduck/.gitlab-ci.yml
  - local: /ci/test/hadolint/.gitlab-ci.yml
  - local: /ci/test/sonar/.gitlab-ci.yml
  - local: /ci/test/clamav/.gitlab-ci.yml
  - local: /ci/dast/anchore/.gitlab-ci.yml
  - local: /ci/dast/zap/.gitlab-ci.yml
  - local: /ci/deploy/.gitlab-ci.yml
  - local: /ci/version/.gitlab-ci.yml
  - local: /ci/docs/.gitlab-ci.yml