image: "maven"

stages:
  - version
  - build
  - test
  - package
  - dast
  - repackage

variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/"
  DOCKER_IMAGE_NAME: ${CI_REGISTRY_IMAGE}/${CI_COMMIT_REF_SLUG}:${CI_COMMIT_SHA}
  DOCKER_IMAGE_LATEST: ${CI_REGISTRY_IMAGE}/${CI_COMMIT_REF_SLUG}:latest

before_script:
  - if [ $(command -v mvn)  ] && [ -f "version" ] ; then mvn -B versions:set -DnewVersion=$(cat version) -DprocessAllModules ; fi


include:
  - local: /ci/test/.gitlab-ci.yml
  - local: /ci/dast/.gitlab-ci.yml
  - local: /ci/build/.gitlab-ci.yml
  - local: /ci/package/.gitlab-ci.yml
  - local: /ci/version/.gitlab-ci.yml
  - local: /ci/docs/.gitlab-ci.yml