image: "maven"

variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/"

before_script:
  - if [ ! "${CI_COMMIT_TAG}" ]; then VERSION_TAG=$(git describe --tags --abbrev=0)-${CI_COMMIT_REF_SLUG}-${GIT_COMMIT_SHORT_SHA}; else VERSION_TAG=${CI_COMMIT_TAG} fi
  - mvn -B versions:set -DnewVersion=${VERSION_TAG} -DprocessAllModules

install:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean org.jacoco:jacoco-maven-plugin:prepare-agent install
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - ".m2/"
  artifacts:
    when: on_success
    expire_in: 5 days
    paths:
      - "*/target"
      - "*/*/target"
      - "*/*/*/target"

sonar_scan:
  stage: test
  only:
    refs:
      - develop
    variables:
      - $SONAR_URL
      - $SONAR_TOKEN
      - $SONAR_PROJECT_KEY
  dependencies:
    - install
  script:
    - ./ci/test/sonar_scan.sh

clamav_scan:
  variables:
    SCAN_LOG: "av.log"
    DEFINITIONS_PATH: ".clamav/"
  stage: test
  dependencies:
    - install
  image:
    name: alpine
  cache:
    key: clamav-definitions
    paths:
      - ${DEFINITIONS_PATH}
  before_script: []
  script:
    - ./ci/test/clamav_scan.sh ${SCAN_LOG} ${DEFINITIONS_PATH}
  artifacts:
    paths:
      - ${SCAN_LOG}

include:
  - local: /ci/test/blackduck/.gitlab-ci.yml
  - local: /ci/deploy/.gitlab-ci.yml