image: "maven"

variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/"

install:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean org.jacoco:jacoco-maven-plugin:prepare-agent install
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - ".m2/"
  artifacts:
    when: on_success
    expire_in: 5 days
    paths:
      - "*/target"
      - "*/*/target"
      - "*/*/*/target"

sonar_scan:
  stage: test
  only:
    refs:
      - develop
    variables:
      - $SONAR_URL
      - $SONAR_TOKEN
      - $SONAR_PROJECT_KEY
  dependencies:
    - install
  script:
    - ./ci/test/sonar_scan.sh

clamav_scan:
  variables:
    SCAN_LOG: "av.log"
    DEFINITIONS_PATH: ".clamav/"
  stage: test
  dependencies:
    - install
  image:
    name: alpine
  cache:
    key: clamav-definitions
    paths:
      - ${DEFINITIONS_PATH}
  script:
    - ./ci/test/clamav_scan.sh ${SCAN_LOG} ${DEFINITIONS_PATH}
  artifacts:
    paths:
      - ${SCAN_LOG}

black_duck_scan:
  stage: test
  only:
    refs:
      - develop
    variables:
      - $BLACK_DUCK_URL
      - $BLACK_DUCK_PROJECT_NAME
      - $BLACK_DUCK_TOKEN
  dependencies:
    - install
  script:
    - ./ci/test/black_duck_scan.sh
