image: "maven"

variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/"

install:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean org.jacoco:jacoco-maven-plugin:prepare-agent install
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - ".m2/"
  artifacts:
    when: on_success
    expire_in: 5 days
    paths:
      - "*/target"
      - "*/*/target"
      - "*/*/*/target"

sonar_scan:
  stage: test
  only:
    - develop
  dependencies:
    - install
  script:
    - mvn $MAVEN_CLI_OPTS sonar:sonar -Dsonar.projectKey="$SONAR_PROJECT_KEY"  -Dsonar.host.url="$SONAR_URL"  -Dsonar.login="$SONAR_TOKEN"

clamav_scan:
  stage: test
  dependencies:
    - install
  image:
    name: alpine
  script:
    - apk add --no-cache clamav rsyslog wget clamav-libunrar
    - /usr/bin/freshclam
    - /usr/bin/clamscan -vr . --log=av.log
  artifacts:
    paths:
      - "av.log"