image: "maven"

stages:
  - version
  - build
  - test
  - deploy

variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/"

before_script:
  - if [ $(command -v mvn)  ] && [ -f "version" ] ; then mvn -B versions:set -DnewVersion=$(cat version) -DprocessAllModules ; fi

install:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean org.jacoco:jacoco-maven-plugin:prepare-agent install
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - ".m2/"
  artifacts:
    when: on_success
    expire_in: 5 days
    paths:
      - "*/target"
      - "*/*/target"
      - "*/*/*/target"

sonar_scan:
  stage: test
  only:
    refs:
      - develop
    variables:
      - $SONAR_URL
      - $SONAR_TOKEN
      - $SONAR_PROJECT_KEY
  script:
    - ./ci/test/sonar_scan.sh

clamav_scan:
  variables:
    SCAN_LOG: "av.log"
    DEFINITIONS_PATH: ".clamav/"
  stage: test
  dependencies:
    - install
  image:
    name: alpine
  cache:
    key: clamav-definitions
    paths:
      - ${DEFINITIONS_PATH}
  before_script: []
  script:
    - ./ci/test/clamav_scan.sh ${SCAN_LOG} ${DEFINITIONS_PATH}
  artifacts:
    paths:
      - ${SCAN_LOG}

include:
  - local: /ci/test/blackduck/.gitlab-ci.yml
  - local: /ci/deploy/.gitlab-ci.yml
  - local: /ci/version/.gitlab-ci.yml