image: "maven"

variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/"

install:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean org.jacoco:jacoco-maven-plugin:prepare-agent install
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - ".m2/"
  artifacts:
    when: on_success
    expire_in: 5 days
    paths:
      - "*/target"
      - "*/*/target"
      - "*/*/*/target"

sonar_scan:
  stage: test
  only:
    refs:
      - develop
    variables:
      - $SONAR_URL
      - $SONAR_TOKEN
      - $SONAR_PROJECT_KEY
  dependencies:
    - install
  script:
    - ./ci/test/sonar_scan.sh

clamav_scan:
  stage: test
  dependencies:
    - install
  image:
    name: alpine
  script:
    - ./ci/test/clamav_scan.sh av.log
  artifacts:
    paths:
      - "av.log"
