image: "maven"

stages:
  - version
  - build
  - test
  - deploy
  - dast

variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/"

before_script:
  - if [ $(command -v mvn)  ] && [ -f "version" ] ; then mvn -B versions:set -DnewVersion=$(cat version) -DprocessAllModules ; fi


include:
  - local: /ci/build/build/.gitlab-ci.yml
  - local: /ci/test/blackduck/.gitlab-ci.yml
  - local: /ci/test/hadolint/.gitlab-ci.yml
  - local: /ci/test/sonar/.gitlab-ci.yml
  - local: /ci/test/clamav/.gitlab-ci.yml
  - local: /ci/dast/anchore/.gitlab-ci.yml
  - local: /ci/dast/zap/.gitlab-ci.yml
  - local: /ci/deploy/.gitlab-ci.yml
  - local: /ci/version/.gitlab-ci.yml
  - local: /ci/docs/.gitlab-ci.yml