version: '3.2'
services:
  chaosengine:
    build: .
    ports:
    - "8080:8080"
    - "8081:8081"
    env_file: .env
    depends_on:
    - vault
    - datadog
    labels:
      com.datadoghq.ad.logs: |
        [
          {
            "source":"Chaos Engine",
            "service": "chaosengine"
          }
        ]
  datadog:
    image: datadog/agent:latest
    environment:
      DD_LOGS_ENABLED: "true"
      DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL: "true"
      DD_AC_EXCLUDE: "image:datadog/agent image:vault"
      DD_ENABLE_PAYLOADS_EVENTS: "false"
      DD_ENABLE_PAYLOADS_SERIES: "false"
      DD_ENABLE_PAYLOADS_SERVICE_CHECKS: "false"
      DD_ENABLE_PAYLOADS_SKETCHES: "false"
    env_file: .datadog_api_key
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
      read_only: true
    - type: bind
      source: /proc
      target: /host/proc
      read_only: true
    - type: bind
      source: /opt/datadog-agent/run
      target: /opt/datadog-agent/run
    - type: bind
      source: /sys/fs/cgroup/
      target: /host/sys/fs/cgroup
      read_only: true
  vault:
    image: vault:0.9.6
    ports:
    - "8200:8200"
    cap_add:
    - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "00000000-0000-0000-0000-000000000000"