version: '3.4'
services:
  chaosengine:
    command: ["-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5005", "-jar", "chaosengine.jar"]
    ports:
    - "8080:8080"
    - "5005:5005"
