site_name: My Docs

theme:
  name: 'material'
  palette:
    primary: 'blue grey'
    accent: 'deep orange'
  logo:
    icon: 'cloud_off'

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.details
  - pymdownx.superfences
