site_name: Chaos Engine
site_description: 'A tool for automated Chaos Experimentation'
repo_url: https://gitlab.gemaltocloud.com/chaos/chaos-engine
repo_name: GitLab

strict: true

theme:
  name: 'material'
  palette:
    primary: 'blue grey'
    accent: 'deep orange'
  feature:
    tabs: true
  logo:
    icon: 'cloud_off'

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.details
  - pymdownx.superfences
