version:
  stage: version
  image: alpine
  only:
    - branches
    - tags
    - merge_requests
  before_script:
    - apk add --no-cache git
  script:
    - touch version
    - |
      if [ -z "${CI_COMMIT_TAG}" ] ; then
        VERSION=$(git describe --tags)
      else
        VERSION=${CI_COMMIT_TAG}
      fi
      if [ "${CI_COMMIT_REF_SLUG}" != "master" ] ; then
        VERSION=${VERSION}-${CI_COMMIT_REF_SLUG}
      fi
    - echo $VERSION > version
  artifacts:
    name: version
    expire_in: 5 days
    paths:
      - version