Documentation: &documentation
  image: python:3-alpine
  stage: test
  variables:
    BUILD_PATH: '.public'
  script:
    - ./ci/docs/mkdocs_build.sh ${BUILD_PATH-public}
  artifacts:
    paths:
      - ${BUILD_PATH}
    expire_in: 5 days

pages:
  <<: *documentation
  variables:
    BUILD_PATH: 'public'
  stage: deploy
  only:
    refs:
      - 'master'
