---
apiVersion: v1
kind: Secret
metadata:
  name: chaos-engine-secrets
  labels:
    app: "chaosengine"
type: Opaque
stringData:
  vault-token: "00000000-0000-0000-0000-000000000000"

---
apiVersion: v1
kind: Service
metadata:
  name: chaosengine-lb
  labels:
    app: chaosengine-lb
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: chaosengine
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaosengine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chaosengine
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: chaosengine
    spec:
      containers:
        - name: chaosengine
          image: thalesgroup/chaos-engine:latest
          env:
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: chaos-engine-secrets
                  key: vault-token
            - name: VAULT_SCHEME
              value: http
            - name: VAULT_HOST
              value: vault
            - name: VAULT_PORT
              value: "8200"
            - name: VAULT_10
              value: "true"
            - name: CHAOS_SECURITY_ENABLED
              value: "false"
            - name: automatedMode
              value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: vault-lb
  labels:
    app: vault-lb
spec:
  ports:
    - port: 8200
      targetPort: 8200
  selector:
    app: vault
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: vault
  labels:
    app: vault-chaos
spec:
  ports:
    - port: 8200
      protocol: TCP
      targetPort: 8200
  selector:
    app: vault

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
        - name: vault
          image: vault:latest
          env:
            - name: VAULT_DEV_ROOT_TOKEN_ID
              valueFrom:
                secretKeyRef:
                  name: chaos-engine-secrets
                  key: vault-token


