build:
  stage: deploy
  variables:
    KANIKO_OPTS: "--no-push"
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - ./ci/deploy/docker_build.sh
#  only:
#    - tags
