---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tags: 3.5.4-jdk-8-alpine

inputs:
  - name: chaos-engine

caches:
  - path: maven

params:

run:
  path: chaos-engine/ci/build.sh

outputs:
  - name: chaos-engine/target