# Used for creating and storing a docker image of the Chaos Engine
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: git-chaos-engine
  type: git
  source:
    uri: ((gitlab.uri))
    branch: ((gitlab.branch))
    private_key: |
      ((gitlab.private_key))
    ignored_paths:
    - ci/**

- name: slack-alert
  type: slack-notification
  source:
    url: ((slack.webhookuri))

- name: docker-chaos-engine
  type: docker-image
  source:
    repository: ((docker.repository))
    aws_access_key_id: ((aws_poweruser.aws_access_key_id))
    aws_secret_access_key: ((aws_poweruser.aws_secret_access_key))

jobs:
- name: chaos-engine-build
  public: true
  plan:
  - get: git-chaos-engine
    trigger: true
    on_failure:
      put: slack-alert
      params:
        text: Git Pull failure.
  - put: docker-chaos-engine
    params:
      build: git-chaos-engine
      target_name: ((gitlab.branch))
    on_failure:
      put: slack-alert
      params:
        text: Build failure.
