resources:
  - name: chaos-engine
    type: git
    source:
      uri: git@gitlab.sascloud.io:chaos/chaos-engine.git
      branch: develop
      private_key: ((ssh_key))

  - name: chaosengine
    type: docker-image
    source:
      repository: 333400148126.dkr.ecr.us-east-2.amazonaws.com/gemalto/chaos
      aws_access_key_id: ((aws_access_key_id))
      aws_secret_access_key: ((aws_secret_access_key))

jobs:
  - name: chaos-engine-test
    public: true
    plan:
    - get: chaos-engine
      trigger: true
    - task: Unit Test
      file: chaos-engine/ci/unitTest.yml
      on_success:
        task: Build
        file: chaos-engine/ci/build.yml
    - put: chaosengine
      params:
        build: chaosengine/
        build_args:
          JAR_FILE: target/chaosengine.jar