resource_types:
- name: concourse-pipeline
  type: docker-image
  source:
    repository: concourse/concourse-pipeline-resource

resources:
- name: chaos-concourse-team
  type: concourse-pipeline
  source:
    target: "http://concourse-web:8080"
    insecure: "true"
    teams:
    - name: main
      username: test
      password: test

- name: git-chaos-engine
  type: git
  source:
    uri: git@gitlab.sascloud.io:chaos/chaos-engine.git
    branch: ((git_branch))
    private_key: ((gitlab.private_key))
    paths:
    - ci/**

jobs:
- name: set-build-pipeline
  plan:
  - get: git-chaos-engine
    trigger: true
  - put: chaos-concourse-team
    params:
      pipelines_file: git-chaos-engine/ci/pipelines.yml
