resources:
  - name: chaos-engine
    type: git
    source:
      uri: git@gitlab.sascloud.io:chaos/chaos-engine.git
      branch: develop
      private_key: ((ssh_key))

  - name: chaosengine
    type: docker-image
    source:
      repository: 333400148126.dkr.ecr.us-east-2.amazonaws.com/gemalto/chaos
      aws_access_key_id: ((aws_access_key_id))
      aws_secret_access_key: ((aws_secret_access_key))

jobs:
- name: chaos-engine-test
  public: true
  plan:
  - get: chaos-engine
    trigger: true
  - task: Build
    file: chaos-engine/ci/build.yml
  - put: chaosengine

- name: chaos-docker-build
  public: true
  plan:
    - put: chaosengine
      params:
        build: jarfile/
        build_args:
          cache: true
          JAR_FILE: /tmp/chaosengine.jar