zap_scan:
  stage: dast
  image: owasp/zap2docker-weekly
  services:
    - name: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
      alias: chaos-engine
  only:
    - branches
    - tags
    - merge_requests
  variables:
    # Do not change, ZAP tool is expecting this directory. If not present file options are skipped.
    ZAP_WORK_DIR: "/zap/wrk/"
    ZAP_REPORT_FILE: "zap_report.html"
    # Containers in the runner pod are unable to resolve hostnames of neighbour containers, the Engine instance must be referenced thru localhost
    CHAOS_ENGINE_API_URL: "http://localhost:8080/v2/api-docs"
    # With current GL setup it ussualy takes 13 minutes until the Engine API is rechable
    CHAOS_ENGINE_STARTUP_TIMEOUT: "900"
  artifacts:
    paths:
      - $ZAP_REPORT_FILE
  script:
    - ./ci/dast/zap/zap_scan.sh