zap_scan:
  stage: dast
  image: owasp/zap2docker-weekly
  retry:
    max: 2
    when: runner_system_failure
  services:
    - name: $DOCKER_IMAGE_NAME
      alias: chaos-engine
  only:
    - branches
    - tags
    - merge_requests
  dependencies: []
  variables:
    # Do not change, ZAP tool is expecting this directory. If not present file options are skipped.
    ZAP_WORK_DIR: "/zap/wrk/"
    ZAP_REPORT_FILE: "zap_report.html"
  artifacts:
    paths:
      - $ZAP_REPORT_FILE
  script:
    - ./ci/dast/zap/zap_scan.sh